//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int ID { get; set; }
        public string MaHoaDon { get; set; }
        public string LoaiChiTiet { get; set; }
        public string TenDanhMuc { get; set; }
        public Nullable<decimal> ChiSoCu { get; set; }
        public Nullable<decimal> ChiSoMoi { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string AmhChiSo { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
