//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongViec()
        {
            this.LichSuThietBis = new HashSet<LichSuThietBi>();
            this.PhieuThuChis = new HashSet<PhieuThuChi>();
        }
    
        public string MaCongViec { get; set; }
        public string MaPhong { get; set; }
        public string MaTaiSan { get; set; }
        public string MaCuDan { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string AnhBaoHong { get; set; }
        public Nullable<decimal> TienDenBu { get; set; }
        public string NguyenNhan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayBao { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
    
        public virtual CuDan CuDan { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual TaiSan TaiSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThietBi> LichSuThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThuChi> PhieuThuChis { get; set; }
    }
}
