//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucDichVu()
        {
            this.HopDong_DichVu = new HashSet<HopDong_DichVu>();
        }
    
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string DonViTinh { get; set; }
        public string HinhThucTinh { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_DichVu> HopDong_DichVu { get; set; }
    }
}
