//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong_CuDan
    {
        public int ID { get; set; }
        public string MaHopDong { get; set; }
        public string MaCuDan { get; set; }
        public string VaiTro { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
        public Nullable<System.DateTime> NgayRoiKhoi { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CuDan CuDan { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
