//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.HopDong_CuDan = new HashSet<HopDong_CuDan>();
            this.HopDong_DichVu = new HashSet<HopDong_DichVu>();
            this.HopDong_TaiSan = new HashSet<HopDong_TaiSan>();
            this.HoaDons = new HashSet<HoaDon>();
            this.PhuLucHopDongs = new HashSet<PhuLucHopDong>();
        }
    
        public string MaHopDong { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public Nullable<decimal> GiaThue { get; set; }
        public Nullable<decimal> GiaDienChot { get; set; }
        public Nullable<decimal> GiaNuocChot { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
        public string MaNguoiDaiDien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_CuDan> HopDong_CuDan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_DichVu> HopDong_DichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong_TaiSan> HopDong_TaiSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuLucHopDong> PhuLucHopDongs { get; set; }
    }
}
