//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong_TaiSan
    {
        public int ID { get; set; }
        public string MaHopDong { get; set; }
        public string MaTaiSan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TinhTrangBanDau { get; set; }
        public string TinhTrangKhiTra { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public Nullable<System.DateTime> NgayThuHoi { get; set; }
        public Nullable<decimal> TienDenBu { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual TaiSan TaiSan { get; set; }
    }
}
