//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong_DichVu
    {
        public int ID { get; set; }
        public string MaHopDong { get; set; }
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string HinhThucTinh { get; set; }
        public Nullable<System.DateTime> NgayNgung { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DanhMucDichVu DanhMucDichVu { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
