//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThietBi
    {
        public int ID { get; set; }
        public string MaTaiSan { get; set; }
        public string MaPhong { get; set; }
        public string LoaiSuKien { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public string NguoiThucHien { get; set; }
        public string MaCongViec { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TaiSan TaiSan { get; set; }
        public virtual CongViec CongViec { get; set; }
    }
}
