//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThuChi()
        {
            this.SoQuys = new HashSet<SoQuy>();
        }
    
        public string MaPhieu { get; set; }
        public string LoaiPhieu { get; set; }
        public string MaHoaDon { get; set; }
        public string MaCongViec { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string NguoiNopNhan { get; set; }
        public string GhiChu { get; set; }
        public string PhuongThuc { get; set; }
        public string NoiDung { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoQuy> SoQuys { get; set; }
        public virtual CongViec CongViec { get; set; }
    }
}
