//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.TaiSans = new HashSet<TaiSan>();
            this.HoaDons = new HashSet<HoaDon>();
            this.LichSuThietBis = new HashSet<LichSuThietBi>();
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string MaToaNha { get; set; }
        public string MaLoaiPhong { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<double> SoDienCu { get; set; }
        public Nullable<double> SoNuocCu { get; set; }
        public string ACTD_Cu { get; set; }
        public string ACTN_Cu { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<decimal> GiaThue { get; set; }
    
        public virtual ToaNha ToaNha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiSan> TaiSans { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThietBi> LichSuThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
    }
}
