//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuLucHopDong
    {
        public int ID { get; set; }
        public string MaHopDong { get; set; }
        public string LoaiPhuLuc { get; set; }
        public Nullable<decimal> GiaThueMoi { get; set; }
        public Nullable<decimal> GiaCocMoi { get; set; }
        public Nullable<decimal> GiaNuocMoi { get; set; }
        public Nullable<decimal> GiaDienMoi { get; set; }
        public Nullable<System.DateTime> ThoiGianMoi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiThucHien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
