//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoQuy
    {
        public int ID { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string LoaiGiaoDich { get; set; }
        public Nullable<decimal> Thu { get; set; }
        public Nullable<decimal> Chi { get; set; }
        public Nullable<decimal> SoDu { get; set; }
        public string NoiDung { get; set; }
        public string NguoiLap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuThuChi PhieuThuChi { get; set; }
    }
}
