//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaTaiKhoan { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string MaQuyen { get; set; }
        public string MaCuDan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CuDan CuDan { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
